theme: jekyll-theme-hacker
title: Hi, I am PGamerX..
description: I am a self learning developer and this is my portfolio.
show_downloads: false
markdown_extensions:
  - meta
github:
  is_project_page: false
